### ISSUE TITLE
Can't dump

### ISSUE THREAD

**Issue by akafester** [dvdgeisler/DirigeraClient#71]
Trying to dump from my Hub, but i keep getting the error that the name can't be resolved. 
Even if I specify the --dirigera.hostname= variable. 

How can i resolve this issue?

**Comment by TheMrBooyah** [comment]
Could you provide us with the full command you're trying to use?

**Comment by akafester** [comment]
> Could you provide us with the full command you're trying to use?
> 
> 
> 
> Also the HUB is connected to the network?

Yes, the hub is connected and discovered. It's just when the script tries to connect, it uses the name of the hub instead of the IP. It fails because it can't resolve the name and then just stops. 

Command: java -jar dirigera-client-dump.jar
OR:		 java -jar dirigera-client-dump.jar --dirigera.hostname=THE IP 

As per documentation.
Tried on 2 different linux machines. Java version is verified to be v17.

**Comment by TheMrBooyah** [comment]
I think I ran into this problem as well with the addon as well.
Try also adding `--dirigera.port=8443`

**Comment by akafester** [comment]
> I think I ran into this problem as well with the addon as well.
> 
> Try also adding `--dirigera.port=8443`

I did already try that, and it didn't work. But now it does. 
I did setup a local DNS resolver on my router, so i'm not sure if that's the reason, but it works now. I will get the dump, and clean it up a bit before posting. 
Is it true that the script doesn't create a text/json file after a successful run?

**Comment by TheMrBooyah** [comment]
It is indeed not writing a file. The console output is the "json"
